// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmcwhetcnavspkoyywhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtY3doZXRjbmF2c3Brb3l5d2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjY1OTYsImV4cCI6MjA1NDA0MjU5Nn0.edqXHCz7FOVXnd1Pr5ptHRRVFTkcoxhwjxc9YwPCyyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);